/**
 * Weather parameters reference for different clothing subcategories
 * Each subcategory has a weatherType object that matches the schema in closet.js
 */

const subCategoryWeatherTypes = {
    // Shirt subcategories
    "T-Shirt": {
      maxTemp: 95,
      minTemp: 65,
      maxHumidity: 100,
      minHumidity: 0,
      maxUvIndex: 11,
      minUvIndex: 0,
      maxWind: 15,
      precipType: "none",
      precipIntensity: "none",
    },
    "Tank Top": {
      maxTemp: 100,
      minTemp: 75,
      maxHumidity: 100,
      minHumidity: 0,
      maxUvIndex: 11,
      minUvIndex: 3,
      maxWind: 10,
      precipType: "none", // Must not be worn in rain or snow
      precipIntensity: "none",
    },
    "Long Sleeve": {
      maxTemp: 75,
      minTemp: 45,
      maxHumidity: 80,
      minHumidity: 0,
      maxUvIndex: 7,
      minUvIndex: 0,
      maxWind: 20,
      precipType: "none",
      precipIntensity: "none",
    },
    "Turtleneck": {
      maxTemp: 65,
      minTemp: 32,
      maxHumidity: 70,
      minHumidity: 0,
      maxUvIndex: 5,
      minUvIndex: 0,
      maxWind: 25,
      precipType: "none",
      precipIntensity: "none",
    },
    "Button-up": {
      maxTemp: 85,
      minTemp: 55,
      maxHumidity: 90,
      minHumidity: 0,
      maxUvIndex: 9,
      minUvIndex: 0,
      maxWind: 20,
      precipType: "none",
      precipIntensity: "none",
    },
    "Polo": {
      maxTemp: 90,
      minTemp: 60,
      maxHumidity: 95,
      minHumidity: 0,
      maxUvIndex: 10,
      minUvIndex: 0,
      maxWind: 15,
      precipType: "none", // Must not be worn in rain or snow
      precipIntensity: "none",
    },
    "Blouse": {
      maxTemp: 85,
      minTemp: 60,
      maxHumidity: 90,
      minHumidity: 0,
      maxUvIndex: 9,
      minUvIndex: 0,
      maxWind: 15,
      precipType: "none",
      precipIntensity: "none",
    },
  
    // Pants subcategories
    "Jeans": {
      maxTemp: 80,
      minTemp: 32,
      maxHumidity: 85,
      minHumidity: 0,
      maxUvIndex: 11,
      minUvIndex: 0,
      maxWind: 30,
      precipType: "any",
      precipIntensity: "light",
    },
    "Khakis": {
      maxTemp: 85,
      minTemp: 50,
      maxHumidity: 80,
      minHumidity: 0,
      maxUvIndex: 9,
      minUvIndex: 0,
      maxWind: 20,
      precipType: "none",
      precipIntensity: "none",
    },
    "Trousers": {
      maxTemp: 75,
      minTemp: 45,
      maxHumidity: 75,
      minHumidity: 0,
      maxUvIndex: 8,
      minUvIndex: 0,
      maxWind: 25,
      precipType: "none",
      precipIntensity: "none",
    },
    "Leggings": {
      maxTemp: 75,
      minTemp: 40,
      maxHumidity: 90,
      minHumidity: 0,
      maxUvIndex: 8,
      minUvIndex: 0,
      maxWind: 20,
      precipType: "none",
      precipIntensity: "none",
    },
    "Shorts": {
      maxTemp: 100,
      minTemp: 70,
      maxHumidity: 100,
      minHumidity: 0,
      maxUvIndex: 11,
      minUvIndex: 3,
      maxWind: 15,
      precipType: "none", // Must not be worn in rain or snow
      precipIntensity: "none",
    },
  
    // Sweater subcategories
    "Cardigan": {
      maxTemp: 70,
      minTemp: 45,
      maxHumidity: 80,
      minHumidity: 0,
      maxUvIndex: 7,
      minUvIndex: 0,
      maxWind: 20,
      precipType: "none",
      precipIntensity: "none",
    },
    "Lightweight": {
      maxTemp: 75,
      minTemp: 50,
      maxHumidity: 85,
      minHumidity: 0,
      maxUvIndex: 8,
      minUvIndex: 0,
      maxWind: 15,
      precipType: "none",
      precipIntensity: "none",
    },
    "Turtleneck Sweater": {
      maxTemp: 60,
      minTemp: 30,
      maxHumidity: 75,
      minHumidity: 0,
      maxUvIndex: 6,
      minUvIndex: 0,
      maxWind: 25,
      precipType: "any",
      precipIntensity: "light",
    },
  
    // Skirt subcategories
    "Mini": {
      maxTemp: 95,
      minTemp: 70,
      maxHumidity: 95,
      minHumidity: 0,
      maxUvIndex: 11,
      minUvIndex: 3,
      maxWind: 10,
      precipType: "none", // Must not be worn in rain or snow
      precipIntensity: "none",
    },
    "Midi": {
      maxTemp: 90,
      minTemp: 60,
      maxHumidity: 90,
      minHumidity: 0,
      maxUvIndex: 10,
      minUvIndex: 0,
      maxWind: 15,
      precipType: "none", // Must not be worn in rain or snow
      precipIntensity: "none",
    },
    "Maxi": {
      maxTemp: 85,
      minTemp: 55,
      maxHumidity: 85,
      minHumidity: 0,
      maxUvIndex: 9,
      minUvIndex: 0,
      maxWind: 20,
      precipType: "light",
      precipIntensity: "light",
    },
  
    // Dress subcategories
    "Mini Dress": {
      maxTemp: 95,
      minTemp: 70,
      maxHumidity: 95,
      minHumidity: 0,
      maxUvIndex: 11,
      minUvIndex: 3,
      maxWind: 10,
      precipType: "none",
      precipIntensity: "none",
    },
    "Midi Dress": {
      maxTemp: 90,
      minTemp: 60,
      maxHumidity: 90,
      minHumidity: 0,
      maxUvIndex: 10,
      minUvIndex: 0,
      maxWind: 15,
      precipType: "none",
      precipIntensity: "none",
    },
    "Maxi Dress": {
      maxTemp: 85,
      minTemp: 55,
      maxHumidity: 85,
      minHumidity: 0,
      maxUvIndex: 9,
      minUvIndex: 0,
      maxWind: 20,
      precipType: "light",
      precipIntensity: "light",
    },
    "Sleeveless": {
      maxTemp: 100,
      minTemp: 75,
      maxHumidity: 100,
      minHumidity: 0,
      maxUvIndex: 11,
      minUvIndex: 3,
      maxWind: 10,
      precipType: "none",
      precipIntensity: "none",
    },
  
    // Shoes subcategories
    "Tennis Shoes": {
      maxTemp: 100,
      minTemp: 32,
      maxHumidity: 100,
      minHumidity: 0,
      maxUvIndex: 11,
      minUvIndex: 0,
      maxWind: 30,
      precipType: "any",
      precipIntensity: "moderate",
    },
    "Loafer": {
      maxTemp: 85,
      minTemp: 50,
      maxHumidity: 80,
      minHumidity: 0,
      maxUvIndex: 9,
      minUvIndex: 0,
      maxWind: 15,
      precipType: "none",
      precipIntensity: "none",
    },
    "Sandal": {
      maxTemp: 100,
      minTemp: 70,
      maxHumidity: 100,
      minHumidity: 0,
      maxUvIndex: 11,
      minUvIndex: 3,
      maxWind: 15,
      precipType: "none", // Must not be worn in rain or snow
      precipIntensity: "none",
    },
    "Boot": {
      maxTemp: 65,
      minTemp: 0,
      maxHumidity: 100,
      minHumidity: 0,
      maxUvIndex: 7,
      minUvIndex: 0,
      maxWind: 35,
      precipType: "any",
      precipIntensity: "heavy",
    },
  
    // Jacket subcategories
    "Winter": {
      maxTemp: 45,
      minTemp: -10,
      maxHumidity: 100,
      minHumidity: 0,
      maxUvIndex: 5,
      minUvIndex: 0,
      maxWind: 40,
      precipType: "snow",
      precipIntensity: "heavy",
    },
    "Rain": {
      maxTemp: 75,
      minTemp: 40,
      maxHumidity: 100,
      minHumidity: 60,
      maxUvIndex: 7,
      minUvIndex: 0,
      maxWind: 30,
      precipType: "rain",
      precipIntensity: "moderate",
    },
    "Blazer": {
      maxTemp: 80,
      minTemp: 55,
      maxHumidity: 85,
      minHumidity: 0,
      maxUvIndex: 8,
      minUvIndex: 0,
      maxWind: 15,
      precipType: "none", // Must not be worn in rain or snow
      precipIntensity: "none",
    }
  };
  
  export default subCategoryWeatherTypes;